// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Keynez user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail();
    return {
      content: [{ type: "text", text: `Signed in as ${email ?? userId}` }],
      structuredContent: { user_id: userId, email }
    };
  }
});

// src/lib/mcp/tools/list-hk-districts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
var REGIONS = {
  hk_island: {
    label: "Hong Kong Island",
    districts: [
      "Central",
      "Sheung Wan",
      "Sai Wan",
      "Wan Chai",
      "Causeway Bay",
      "North Point",
      "Quarry Bay",
      "Tai Koo",
      "Sai Wan Ho",
      "Shau Kei Wan",
      "Chai Wan",
      "Aberdeen",
      "Ap Lei Chau",
      "Wong Chuk Hang",
      "Repulse Bay",
      "Stanley"
    ]
  },
  kowloon: {
    label: "Kowloon",
    districts: [
      "Tsim Sha Tsui",
      "Jordan",
      "Yau Ma Tei",
      "Mong Kok",
      "Sham Shui Po",
      "Cheung Sha Wan",
      "Mei Foo",
      "Hung Hom",
      "To Kwa Wan",
      "Kowloon City",
      "Ho Man Tin",
      "Wong Tai Sin",
      "Diamond Hill",
      "Ngau Chi Wan",
      "Kwun Tong",
      "Lam Tin",
      "Ngau Tau Kok",
      "Kowloon Bay"
    ]
  },
  new_territories: {
    label: "New Territories",
    districts: [
      "Tsuen Wan",
      "Kwai Chung",
      "Tsing Yi",
      "Tuen Mun",
      "Yuen Long",
      "Tin Shui Wai",
      "Sheung Shui",
      "Fanling",
      "Tai Po",
      "Sha Tin",
      "Ma On Shan",
      "Tai Wai",
      "Tseung Kwan O",
      "Sai Kung",
      "Clear Water Bay"
    ]
  }
};
var list_hk_districts_default = defineTool2({
  name: "list_hk_districts",
  title: "List Hong Kong districts",
  description: "List Hong Kong districts, optionally filtered by region.",
  inputSchema: {
    region: z.enum(["hk_island", "kowloon", "new_territories"]).optional().describe("Optional region filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ region }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const entries = region ? [[region, REGIONS[region]]] : Object.entries(REGIONS);
    const lines = [];
    const structured = {};
    for (const [key, val] of entries) {
      lines.push(`${val.label}: ${val.districts.join(", ")}`);
      structured[key] = val.districts;
    }
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: { regions: structured }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kfsemsacrjlvkzvewbqp";
var mcp_default = defineMcp({
  name: "keynez-mcp",
  title: "Keynez MCP",
  version: "0.1.0",
  instructions: "Tools for the Keynez Hong Kong property assistant. Use `whoami` to confirm the signed-in user and `list_hk_districts` to enumerate districts by region.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_hk_districts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
